---
label: Site Config
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- type: file
  name: logo
  label: Logo
- name: footer
  label: Footer
  type: text
  hidden: false
  default: ''
- name: favicon
  label: Favicon
  type: file
  hidden: false
  default: ''
- name: navigation
  label: Navigation
  type: field_group_list
  fields:
  - name: text
    label: Text
    type: text
    hidden: false
    default: ''
  - name: link
    label: Link
    type: text
    hidden: false
    default: ''
  - type: select
    config:
      source:
        type: simple
      options:
      - left
      - right
    label: Position
    name: position
  - name: external
    label: External
    type: boolean
    hidden: false
    default: ''
  hidden: false
  default: ''
- name: footer_copy
  type: field_group_list
  fields:
  - name: footer_headline
    type: text
    config:
      required: false
    label: Footer Headline
  - name: footer_text
    type: text
    config:
      required: false
    label: Footer Text
  - name: footer_copyright
    type: text
    config:
      required: false
    label: Footer Copyright
  - name: link
    type: text
    config:
      required: false
    label: Link
  - name: position
    type: select
    default: []
    config:
      required: false
      options: []
      source:
        type: simple
        section: 
        file: 
        path: 
    label: Position
  config:
    min: 
    max: 
    labelField: 
  label: Footer Copy
pages:
- portfolio/config.json
